[package]
name = "sdl2-sys"
version = "0.1.0"
authors = [ "XorTroll", "switchbrew", "SDL2 authors" ]

[lib]
crate_type = ["rlib"]

[build-dependencies]
bindgen = "0.37.4"
cfg-if = "0.1"

[features]
default = []
ttf = []
mixer = []
image = []
