[package]
name = "sdl2"
version = "0.1.0"
authors = [ "XorTroll", "switchbrew", "SDL2 authors" ]
links = "sdl2"

[lib]
crate_type = ["rlib"]

[dependencies]
cfg-if = "0.1"

[build-dependencies]
bindgen = "0.37.4"
cfg-if = "0.1"

[features]
default = []
ttf = []
image = []
